--- 
sudo: required
language: python
services:
  - docker
  
env: 
  - version="" distro="ubuntu-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker